sudo: required
services: 
  - docker

before_install: 
  - docker build -t tracyatrf/multi-container -f ./client/Dockerfile.dev
script:
  - docker run tracyatrf/multi-container npm test --coverage

after_success:
  - docker build -t tracyatrf/multi-client ./client
  - docker build -t tracyatrf/multi-server ./server
  - docker build -t tracyatrf/multi-worker ./worker
  - docker build -t tracyatrf/multi-nginx ./nginx
